### PR TITLE
Updates to peer reputation

### LINKED ISSUE #57: Peer reputation no longer works
Because of a change in the telemetry JSON structure, peer reputation no longer works.

### PR DESCRIPTION
**Pull request by mattrutherford**
Update peer reputation queries to match new telemetry structure

Fixes #57

Allow historic queries

### CODE REVIEW

**Comment by dvdplm** [comment]
Do we care about existing data? Looks like the updated query will not find data recorded with the old structure.

**Comment by mattrutherford** [comment]
Good point - we are supporting older versions of telemetry elsewhere, but this change is actually quite old, so IMO I don't think it's worth supporting. AFAIK peer reputation has not been used much in app, only indirectly in a separate prometheus exporter

**Comment by mattrutherford** [comment]
Endpoint: `/reputation/12D3KooWMDiAaMSrhK3Ez3jBPkra2ts3nDztK9CiPu6CvrRBMpCp` replaced with new query which accepts `Filters` for time range and row limit - results now in the format:

```json
[{"connected":true,"reporting_peer":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp","reputation":3947,"ts":"2020-09-08T10:56:41.997787"},{"connected":true,"reporting_peer":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp","reputation":4172,"ts":"2020-09-08T10:57:11.997947"},{"connected":true,"reporting_peer":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp","reputation":4099,"ts":"2020-09-08T10:57:41.998136"},{"connected":true,"reporting_peer":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp","reputation":4106,"ts":"2020-09-08T10:58:11.998317"},{"connected":true,"reporting_peer":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp","reputation":4184,"ts":"2020-09-08T10:58:41.998473"},{"connected":true,"reporting_peer":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp","reputation":4357,"ts":"2020-09-08T10:59:11.998584"},{"connected":true,"reporting_peer":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp","reputation":4127,"ts":"2020-09-08T10:59:41.998829"},{"connected":true,"reporting_peer":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp","reputation":3983,"ts":"2020-09-08T11:00:11.998994"}]
```

**Comment by mattrutherford** [comment]
TODO: decide if we deprecate the other existing peer reputation queries?

**Comment by dvdplm** [comment]
> TODO: decide if we deprecate the other existing peer reputation queries?

Can you expand on this? We currently have

```
- **`/reputation/{peer_id}`**
  - reported reputation for `peer_id` from the POV of other nodes.
- **`/reputation/logged`**
  - reported reputation for all peers from the POV of all logged (past/present) nodes
- **`/reputation`**
  - reported reputation for all peers unfiltered
```
Superficially both `/reputation/logged` and `/reputation` seem useful to me, can you elaborate on why we should deprecate them?

**Comment by dvdplm** [comment]
Question: what does the reputation value mean (e.g. 4016 from the sample below)? Is it a dimensionless value that is useful only in relation to others or does it have any deeper meaning?

```
   {
      "connected":true,
      "reporting_peer":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp",
      "reputation":4106,
      "ts":"2020-09-08T10:58:11.998317"
   },
```

**Comment by mattrutherford** [comment]
> > TODO: decide if we deprecate the other existing peer reputation queries?
> 
> Can you expand on this? We currently have
> 
> ```
> - **`/reputation/{peer_id}`**
>   - reported reputation for `peer_id` from the POV of other nodes.
> - **`/reputation/logged`**
>   - reported reputation for all peers from the POV of all logged (past/present) nodes
> - **`/reputation`**
>   - reported reputation for all peers unfiltered
> ```
> 
> Superficially both `/reputation/logged` and `/reputation` seem useful to me, can you elaborate on why we should deprecate them?

Only because I think it's easier to work with the data returned by the new query. But no harm in them staying

**Comment by mattrutherford** [comment]
> Question: what does the reputation value mean (e.g. 4016 from the sample below)? Is it a dimensionless value that is useful only in relation to others or does it have any deeper meaning?
> 
> ```
>    {
>       "connected":true,
>       "reporting_peer":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp",
>       "reputation":4106,
>       "ts":"2020-09-08T10:58:11.998317"
>    },
> ```

I'm not 100% sure, but AFAIK if it drops into a negative value that means something is wrong. It would be interesting to see if the values correlate at all with other metrics

**Pull request merged**
